clc
close all

%Following Code is Autogenerated by MATLAB
%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 5);

% Specify sheet and range
opts.Sheet = "PR-all";
opts.DataRange = "A3:E112";

% Specify column names and types
opts.VariableNames = ["BM", "fidecimalDegree", "lambdadecimaDegree", "NormalHeightH", "gmGal"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];

% Import the data
tbl = readtable("C:\Users\tavish.comrie\Documents\GitHub\ENGO423_Geodesy\Lab5\Normal_Heights_Gravity_Line1.xls", opts, "UseExcel", false);

%% Convert to output type
BM = tbl.BM;
fiDD = tbl.fidecimalDegree;
lambdaDD = tbl.lambdadecimaDegree;
NormalHeightH = tbl.NormalHeightH;
gmGal = tbl.gmGal;

%% Clear temporary variables
clear opts tbl
ybar = zeros(size(NormalHeightH,1),1);
C = zeros(size(NormalHeightH,1),1);

%From here it is our own code
for i = 1:size(NormalHeightH)
    ybar(i) = meanNormalGravity(lambdaDD(i),NormalHeightH(i));
end


for i = 1:size(NormalHeightH,1)
    C(i,1) = NormalHeightH(i)*meanNormalGravity(i);

end










function [H] = OrthoHeight(C,g,Hstar)
     while True
          gMean = g+0.0424*Hstar;
          H = C/gMean;

          if (Hstar-H)<0.01
              Hstar = H;
              continue
          else
          end
     end
       
end